### ISSUE TITLE
Where is hubot-post-commit-hook.py script

### ISSUE THREAD

**Issue by ashish1099** [luck3y/hubot-gitolite#1]
I can't find this hook ?

**Comment by luck3y** [comment]
I never quite finished that bit ;)

Something like:

curl -vvvvv -X POST -H "Content-Type: application/json" -d '{"commit":"repo":"test","id":"234432234","branch":"master
","author":"hello","message":"hi this is a test commit"}}' http://127.0.0.1:8080/

Should do it.

**Comment by ashish1099** [comment]
ok cool. let me try that

**Comment by luck3y** [comment]
Also feel free to fork and complete, or send me patches :)
